In [1]:
import torch
from torch import nn

# Linear

In [2]:
m = nn.Linear(2, 3)
m

Linear(in_features=2, out_features=3, bias=True)

In [3]:
input = torch.rand(2)
input

tensor([0.5358, 0.3796])

In [4]:
m(input)

tensor([ 0.8980,  0.1070, -0.1587], grad_fn=<AddBackward0>)

In [5]:
m.weight, m.bias

(Parameter containing:
 tensor([[ 0.6122,  0.0949],
         [ 0.4877,  0.3731],
         [-0.3167, -0.5591]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5340, -0.2960,  0.2232], requires_grad=True))

In [6]:
torch.matmul(m.weight, input) + m.bias

tensor([ 0.8980,  0.1070, -0.1587], grad_fn=<AddBackward0>)

# Convolution

In [7]:
m = nn.Conv1d(in_channels=3, out_channels=2, kernel_size=4)
m.weight, m.bias

(Parameter containing:
 tensor([[[-0.0618,  0.0710, -0.1576,  0.1202],
          [ 0.0042,  0.1777, -0.1358,  0.1538],
          [ 0.1124,  0.1819, -0.0375,  0.2509]],
 
         [[ 0.2410,  0.0919, -0.2155,  0.2886],
          [-0.0923,  0.0185, -0.1231,  0.2772],
          [ 0.0098, -0.2858, -0.2230,  0.2430]]], requires_grad=True),
 Parameter containing:
 tensor([-0.0699, -0.1645], requires_grad=True))

In [8]:
input = torch.rand(3, 7)
input

tensor([[0.5391, 0.1440, 0.7365, 0.6486, 0.4576, 0.6834, 0.1048],
        [0.1956, 0.1331, 0.8039, 0.2506, 0.1295, 0.7127, 0.7451],
        [0.1897, 0.8582, 0.5038, 0.6590, 0.5414, 0.9032, 0.8648]])

In [9]:
m(input)

tensor([[ 0.1466,  0.3548,  0.4633,  0.2248],
        [-0.2334, -0.2130,  0.1988, -0.1244]], grad_fn=<SqueezeBackward1>)

In [10]:
[
    torch.sum(m.weight[0] * input[:, 0:4]) + m.bias[0],
    torch.sum(m.weight[0] * input[:, 1:5]) + m.bias[0],
    torch.sum(m.weight[0] * input[:, 2:6]) + m.bias[0],
    torch.sum(m.weight[0] * input[:, 3:7]) + m.bias[0],
]

[tensor(0.1466, grad_fn=<AddBackward0>),
 tensor(0.3548, grad_fn=<AddBackward0>),
 tensor(0.4633, grad_fn=<AddBackward0>),
 tensor(0.2248, grad_fn=<AddBackward0>)]

In [11]:
[
    torch.sum(m.weight[1] * input[:, 0:4]) + m.bias[1],
    torch.sum(m.weight[1] * input[:, 1:5]) + m.bias[1],
    torch.sum(m.weight[1] * input[:, 2:6]) + m.bias[1],
    torch.sum(m.weight[1] * input[:, 3:7]) + m.bias[1],
]

[tensor(-0.2334, grad_fn=<AddBackward0>),
 tensor(-0.2130, grad_fn=<AddBackward0>),
 tensor(0.1988, grad_fn=<AddBackward0>),
 tensor(-0.1244, grad_fn=<AddBackward0>)]

# Two dimensional

In [12]:
m = nn.Conv2d(2, 3, (2, 4))
m.weight

Parameter containing:
tensor([[[[-2.0411e-01, -2.7462e-02,  1.9147e-01, -1.7199e-01],
          [ 7.2721e-02, -1.9994e-01, -2.3749e-01,  2.0968e-02]],

         [[-5.0866e-02,  1.5459e-01,  1.2333e-01,  6.2885e-02],
          [-1.1503e-01,  9.9345e-02,  2.0866e-01, -1.0110e-01]]],


        [[[ 2.2189e-01,  1.9349e-01, -2.2063e-01, -1.3557e-01],
          [-4.6969e-02,  4.5682e-02, -1.8891e-01,  1.3933e-01]],

         [[-4.7293e-03, -1.8525e-01,  9.5883e-02, -1.7339e-01],
          [ 1.9617e-01,  4.9526e-02, -5.3311e-02, -2.2112e-01]]],


        [[[-1.6013e-01, -1.4089e-01,  4.2193e-03,  1.6141e-01],
          [ 1.3814e-01,  1.2587e-02,  2.3132e-01,  1.3588e-01]],

         [[-4.1097e-05, -1.5928e-01, -1.1762e-01,  3.9201e-02],
          [ 1.4691e-01, -1.6641e-01,  2.2056e-01,  2.4622e-01]]]],
       requires_grad=True)